channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.7
  - pip >=21.1
  - setuptools_scm
  - toml

  # Documentation
  - furo
  - ipython
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - -e ../
